// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDU5bydwLsVds1QcjI-75zTkOePhtOgxg',
    appId: '1:785121927334:android:ca4c80108a96aad9025467',
    messagingSenderId: '785121927334',
    projectId: 'niccioli-enersys',
    storageBucket: 'niccioli-enersys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKttrwRwN9LSF2LsAVH9BPZJnsQdNWkY',
    appId: '1:785121927334:ios:3a086a1210df9fb8025467',
    messagingSenderId: '785121927334',
    projectId: 'niccioli-enersys',
    storageBucket: 'niccioli-enersys.firebasestorage.app',
    androidClientId: '785121927334-5dgm031j38s0lesmmvg3hkoomgrf9e05.apps.googleusercontent.com',
    iosClientId: '785121927334-di026p31nvk443sfon8ptudjll8b7eg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.niccioli',
  );
}
